pipeline {
    agent any

    environment {
        DOCKERTAG = "v2"
    }

    stages {
        stage('Clone Repo') {
            steps {
                checkout scm
            }
        }

        stage('Update Helm Chart Image Tag') {
            steps {
                script {
                    catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                        withCredentials([usernamePassword(
                            credentialsId: 'github',
                            usernameVariable: 'GIT_USERNAME',
                            passwordVariable: 'GIT_PASSWORD'
                        )]) {
                            sh '''
                                git config user.email "abhishekrangra@gmail.com"
                                git config user.name "AbhishekRangra"

                                echo "Before update (values.yaml):"
                                cat helm/mychart/values.yaml

                                sed -i 's+abhishekrangra/js_app.*+abhishekrangra/js_app:'"$DOCKERTAG"'+g' helm/mychart/values.yaml

                                echo "After update (values.yaml):"
                                cat helm/mychart/values.yaml

                                git add helm/mychart/values.yaml
                                git commit -m "Updated image tag to $DOCKERTAG"

                                git push https://$GIT_USERNAME:$GIT_PASSWORD@github.com/$GIT_USERNAME/js_app.git HEAD:main
                            '''
                        }
                    }
                }
            }
        }
    }
}
